version: "2.1"
services:
  localstack:
    container_name: "ambiente-dev-localstack"
    image: localstack/localstack:0.12.2
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4510-4530:4510-4530"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - EDGE_PORT=4572
      - EDGE_BIND_HOST=http://localhost
      - DEFAULT_REGION=sa-east-1
      - SERVICES=s3,lambda,sqs,iam,cloudformation
      - USE_LIGHT_IMAGE=0
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
