services:
  localstack:
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-1
      - EDGE_PORT=4566
      - SERVICES=sqs
    image: "localstack/localstack:latest"
    ports:
      - "4566:4566"
    container_name: docker-localstack
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
version: "3.0"
