service: my-lambda-function
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
